class MockDataService {
  Future<Map<String, dynamic>> fetchAllData() async {
    // Simulate network delay
    await Future.delayed(const Duration(seconds: 1));

    final String gifUrl = 'https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHJndXp4OHRxcXp4NXp4NXp4NXp4NXp4NXp4NXp4NXp4NXp4NXp4JmVwPXYxX2ludGVybmFsX2dpZl9ieV9pZCZjdD1n/3o7TKVUn7iM8FMEU24/giphy.gif';

    return {
      'categories': [
        {'id': 'cat_chest', 'name': 'Chest', 'imageUrl': 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?q=80&w=2070&auto=format&fit=crop'},
        {'id': 'cat_back', 'name': 'Back', 'imageUrl': 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?q=80&w=2070&auto=format&fit=crop'},
        {'id': 'cat_bicep', 'name': 'Bicep', 'imageUrl': 'https://images.unsplash.com/photo-1581009146145-b5ef03a19d7b?q=80&w=2070&auto=format&fit=crop'},
        {'id': 'cat_tricep', 'name': 'Tricep', 'imageUrl': 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=2070&auto=format&fit=crop'},
        {'id': 'cat_shoulders', 'name': 'Shoulders', 'imageUrl': 'https://images.unsplash.com/photo-1532029837206-abbe2b7620e3?q=80&w=2070&auto=format&fit=crop'},
        {'id': 'cat_forearms', 'name': 'Forearms', 'imageUrl': 'https://images.unsplash.com/photo-1590239062391-7f37c8a49c2d?q=80&w=2070&auto=format&fit=crop'},
        {'id': 'cat_cardio', 'name': 'Cardio', 'imageUrl': 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?q=80&w=1974&auto=format&fit=crop'},
        {'id': 'cat_legs', 'name': 'Legs', 'imageUrl': 'https://images.unsplash.com/photo-1434608519344-49d77a699e1d?q=80&w=2074&auto=format&fit=crop'},
        {'id': 'cat_stretching', 'name': 'Stretching', 'imageUrl': 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?q=80&w=2070&auto=format&fit=crop'},
      ],
      'exercises': [
        // CHEST (cat_chest) - 21 exercises
        {
          'id': 'ex_chest_1', 'name': 'Barbell Bench Press', 'categoryId': 'cat_chest',
          'description': 'The fundamental compound movement for building massive chest strength and size.',
          'targetMuscle': 'Pectoralis Major (Mid)', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Lie flat on the bench with feet planted.', 'Grip the bar slightly wider than shoulder width.', 'Lower the bar slowly to mid-chest.', 'Explosively press the bar back up.'],
          'duration': '60s', 'sets': 4, 'reps': 8,
        },
        {
          'id': 'ex_chest_2', 'name': 'Incline Barbell Bench Press', 'categoryId': 'cat_chest',
          'description': 'Shifts the focus to the upper pectoral fibers for a full, well-rounded chest.',
          'targetMuscle': 'Upper Pectorals', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Set the bench to a 30-45 degree angle.', 'Lower the bar to your upper chest.', 'Press upward until arms are fully extended.', 'Control the weight on the way down.'],
          'duration': '60s', 'sets': 4, 'reps': 10,
        },
        {
          'id': 'ex_chest_3', 'name': 'Decline Barbell Bench Press', 'categoryId': 'cat_chest',
          'description': 'Targets the lower portion of the chest, often allowing for heavier weights.',
          'targetMuscle': 'Lower Pectorals', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Secure your legs in the decline bench.', 'Lower the bar to the bottom of your chest.', 'Press the weight back to the starting position.', 'Maintain a stable core throughout.'],
          'duration': '60s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_chest_4', 'name': 'Dumbbell Bench Press', 'categoryId': 'cat_chest',
          'description': 'Provides a greater range of motion and helps correct muscle imbalances.',
          'targetMuscle': 'Pectoralis Major', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Lie back on a flat bench with a dumbbell in each hand.', 'Lower the weights until they are level with your chest.', 'Press them back up, bringing them close together at the top.', 'Keep your elbows at a 45-degree angle.'],
          'duration': '60s', 'sets': 4, 'reps': 12,
        },
        {
          'id': 'ex_chest_5', 'name': 'Incline Dumbbell Press', 'categoryId': 'cat_chest',
          'description': 'The best isolation-compound hybrid for upper chest development.',
          'targetMuscle': 'Upper Chest', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Sit on an incline bench with dumbbells.', 'Press the dumbbells straight up above your shoulders.', 'Lower them slowly to the sides of your upper chest.', 'Drive them back up with power.'],
          'duration': '60s', 'sets': 4, 'reps': 12,
        },
        {
          'id': 'ex_chest_6', 'name': 'Decline Dumbbell Press', 'categoryId': 'cat_chest',
          'description': 'Isolates the lower chest without the restrictions of a barbell.',
          'targetMuscle': 'Lower Chest', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Lie on a decline bench with dumbbells.', 'Press the weights up from your lower chest.', 'Lower them until you feel a deep stretch.', 'Squeeze your chest at the top.'],
          'duration': '60s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_chest_7', 'name': 'Dumbbell Flyes', 'categoryId': 'cat_chest',
          'description': 'An isolation exercise designed to stretch the chest fibers and build inner definition.',
          'targetMuscle': 'Outer/Inner Pectorals', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Lie on a flat bench holding dumbbells with palms facing each other.', 'Lower the weights in a wide arc until you feel a stretch.', 'Bring the weights back together using your chest muscles.', 'Keep a slight bend in your elbows.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_chest_8', 'name': 'Incline Dumbbell Flyes', 'categoryId': 'cat_chest',
          'description': 'Targets the upper chest fibers while providing a deep stretch.',
          'targetMuscle': 'Upper Pectorals', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Lie on an incline bench.', 'Open your arms wide in a flye motion.', 'Focus on pulling with your upper chest.', 'Squeeze hard at the top of the movement.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_chest_9', 'name': 'Cable Crossover (High to Low)', 'categoryId': 'cat_chest',
          'description': 'Excellent for targeting the lower chest and creating a "cut" look.',
          'targetMuscle': 'Lower Chest', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Set cables to the highest position.', 'Step forward and lean slightly.', 'Pull the handles down and together in front of your waist.', 'Control the weight back to the start.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_chest_10', 'name': 'Cable Crossover (Low to High)', 'categoryId': 'cat_chest',
          'description': 'One of the few exercises that directly targets the upper-inner chest.',
          'targetMuscle': 'Upper-Inner Chest', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Set cables to the lowest position.', 'Pull the handles up and toward the center of your chest.', 'Keep your palms facing up.', 'Squeeze your chest at the top.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_chest_11', 'name': 'Pec Deck Machine', 'categoryId': 'cat_chest',
          'description': 'Safe and effective way to isolate the chest with constant tension.',
          'targetMuscle': 'Inner Chest', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Sit with your back against the pad.', 'Place your forearms on the pads.', 'Bring the pads together in a controlled motion.', 'Feel the squeeze in your inner chest.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_chest_12', 'name': 'Chest Press Machine', 'categoryId': 'cat_chest',
          'description': 'A machine alternative to the bench press, great for beginners or drop sets.',
          'targetMuscle': 'Pectoralis Major', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Adjust the seat so the handles are at chest level.', 'Press the handles forward.', 'Slowly return to the start without letting weights touch.', 'Keep your shoulders back.'],
          'duration': '45s', 'sets': 4, 'reps': 12,
        },
        {
          'id': 'ex_chest_13', 'name': 'Smith Machine Bench Press', 'categoryId': 'cat_chest',
          'description': 'Allows you to focus purely on the chest without worrying about stabilization.',
          'targetMuscle': 'Pectoralis Major', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Position the bench under the bar.', 'Unrack the bar and lower it to your chest.', 'Press it back up smoothly.', 'Rotate the bar to lock it when finished.'],
          'duration': '60s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_chest_14', 'name': 'Weighted Dips (Chest Focus)', 'categoryId': 'cat_chest',
          'description': 'An advanced movement that builds immense power in the lower chest.',
          'targetMuscle': 'Lower Chest', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Use a dip belt for added weight.', 'Lean your torso forward significantly.', 'Flare your elbows out slightly.', 'Lower yourself deep and push back up.'],
          'duration': '60s', 'sets': 3, 'reps': 8,
        },
        {
          'id': 'ex_chest_15', 'name': 'Push-Ups (Standard)', 'categoryId': 'cat_chest',
          'description': 'The classic bodyweight chest builder.',
          'targetMuscle': 'Chest (Overall)', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Start in a plank position.', 'Lower your chest to the floor.', 'Keep your core tight and back flat.', 'Push back up to the start.'],
          'duration': '45s', 'sets': 3, 'reps': 20,
        },
        {
          'id': 'ex_chest_16', 'name': 'Incline Push-Ups', 'categoryId': 'cat_chest',
          'description': 'Easier version of push-ups, targeting the lower chest.',
          'targetMuscle': 'Lower Chest', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Place your hands on an elevated surface.', 'Perform a standard push-up motion.', 'Focus on the lower chest contraction.', 'Maintain a straight body line.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_chest_17', 'name': 'Decline Push-Ups', 'categoryId': 'cat_chest',
          'description': 'Harder push-up variation focusing on the upper chest.',
          'targetMuscle': 'Upper Chest', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Place your feet on an elevated surface.', 'Keep your hands on the floor.', 'Lower your chest toward the ground.', 'Push back up forcefully.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_chest_18', 'name': 'Diamond Push-Ups', 'categoryId': 'cat_chest',
          'description': 'Focuses on the inner chest and triceps.',
          'targetMuscle': 'Inner Chest / Triceps', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Place your hands together forming a diamond shape.', 'Lower your chest to your hands.', 'Keep your elbows close to your body.', 'Push back up.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_chest_19', 'name': 'Floor Press (Barbell)', 'categoryId': 'cat_chest',
          'description': 'Develops explosive power by eliminating the bottom part of the press.',
          'targetMuscle': 'Pectorals (Mid-Range)', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Lie on the floor under a power rack.', 'Lower the bar until your elbows touch the floor.', 'Pause for a second.', 'Press the bar back up explosively.'],
          'duration': '60s', 'sets': 3, 'reps': 8,
        },
        {
          'id': 'ex_chest_20', 'name': 'Svend Press', 'categoryId': 'cat_chest',
          'description': 'An isometric-style movement for extreme inner chest activation.',
          'targetMuscle': 'Inner Chest', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Stand and hold a weight plate between your hands at chest height.', 'Squeeze the plate hard as you press it forward.', 'Bring it back to your chest while maintaining the squeeze.', 'Exhale as you press.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_chest_21', 'name': 'Landmine Press', 'categoryId': 'cat_chest',
          'description': 'Saves the shoulders while targeting the upper chest effectively.',
          'targetMuscle': 'Upper Pectorals', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Place one end of a barbell in a landmine attachment.', 'Hold the other end at shoulder height.', 'Press the bar up and away.', 'Control the descent.'],
          'duration': '60s', 'sets': 3, 'reps': 12,
        },

        // BACK (cat_back) - 21 exercises
        {
          'id': 'ex_back_1', 'name': 'Conventional Deadlift', 'categoryId': 'cat_back',
          'description': 'The king of all exercises for building a powerful back and posterior chain.',
          'targetMuscle': 'Lower Back / Spinal Erectors', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Stand with feet hip-width apart.', 'Grip the bar just outside your legs.', 'Keep your back flat and pull the bar up along your shins.', 'Stand tall and lock out.'],
          'duration': '90s', 'sets': 3, 'reps': 5,
        },
        {
          'id': 'ex_back_2', 'name': 'Bent Over Barbell Row', 'categoryId': 'cat_back',
          'description': 'Builds thick lat and middle back muscles.',
          'targetMuscle': 'Latissimus Dorsi / Rhomboids', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Hinge at the hips and keep your back flat.', 'Pull the bar toward your lower stomach.', 'Squeeze your shoulder blades together.', 'Lower the bar with control.'],
          'duration': '60s', 'sets': 4, 'reps': 8,
        },
        {
          'id': 'ex_back_3', 'name': 'One-Arm Dumbbell Row', 'categoryId': 'cat_back',
          'description': 'Allows for a deep stretch and unilateral back development.',
          'targetMuscle': 'Lats / Mid-Back', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Place one hand and knee on a bench.', 'Pull the dumbbell toward your hip.', 'Focus on driving with your elbow.', 'Stretch the arm fully at the bottom.'],
          'duration': '60s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_back_4', 'name': 'Lat Pulldown (Wide Grip)', 'categoryId': 'cat_back',
          'description': 'The standard machine exercise for building back width.',
          'targetMuscle': 'Latissimus Dorsi (Outer)', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Grip the bar wider than shoulders.', 'Pull the bar down to your upper chest.', 'Focus on pulling your elbows down.', 'Don\'t use momentum to swing.'],
          'duration': '45s', 'sets': 4, 'reps': 10,
        },
        {
          'id': 'ex_back_5', 'name': 'Lat Pulldown (Close Grip)', 'categoryId': 'cat_back',
          'description': 'Uses a V-bar to target the lower lat attachments.',
          'targetMuscle': 'Lower Lats', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Attach a V-bar to the machine.', 'Pull the handle down to your mid-chest.', 'Lean back slightly.', 'Squeeze your back at the bottom.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_back_6', 'name': 'Seated Cable Row', 'categoryId': 'cat_back',
          'description': 'Targets the mid-back for better posture and thickness.',
          'targetMuscle': 'Rhomboids / Traps', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Sit with knees slightly bent.', 'Pull the handle toward your abdomen.', 'Squeeze your shoulder blades together.', 'Release slowly.'],
          'duration': '45s', 'sets': 4, 'reps': 12,
        },
        {
          'id': 'ex_back_7', 'name': 'Pull-Ups', 'categoryId': 'cat_back',
          'description': 'The ultimate bodyweight test for back strength.',
          'targetMuscle': 'Lats', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Hang from a bar with palms facing away.', 'Pull your chest up to the bar.', 'Lower yourself slowly.', 'Avoid kicking your legs.'],
          'duration': '60s', 'sets': 3, 'reps': 8,
        },
        {
          'id': 'ex_back_8', 'name': 'Chin-Ups', 'categoryId': 'cat_back',
          'description': 'Variation of pull-ups that targets more of the biceps and lower lats.',
          'targetMuscle': 'Lats / Biceps', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Hang from a bar with palms facing you.', 'Pull your chin above the bar.', 'Lower with control.', 'Keep your core engaged.'],
          'duration': '60s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_back_9', 'name': 'T-Bar Row', 'categoryId': 'cat_back',
          'description': 'A heavy rowing movement using a corner-anchored barbell.',
          'targetMuscle': 'Mid-Back', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Stand over the bar and grip the handle.', 'Pull the weight toward your chest.', 'Keep your back slightly above horizontal.', 'Control the weight down.'],
          'duration': '60s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_back_10', 'name': 'Face Pulls', 'categoryId': 'cat_back',
          'description': 'Excellent for rear delt and upper back health.',
          'targetMuscle': 'Rear Deltoids / Traps', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Use a rope attachment at head height.', 'Pull the rope toward your face.', 'Pull the ends of the rope apart.', 'Squeeze your upper back.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_back_11', 'name': 'Back Extensions', 'categoryId': 'cat_back',
          'description': 'Targets the lower back to improve core stability.',
          'targetMuscle': 'Lower Back (Erectors)', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Place your hips on the pad.', 'Lower your upper body slowly.', 'Raise back up until your body is straight.', 'Don\'t over-arch at the top.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_back_12', 'name': 'Straight Arm Pulldown', 'categoryId': 'cat_back',
          'description': 'Isolates the lats by removing bicep involvement.',
          'targetMuscle': 'Latissimus Dorsi', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Stand facing the cable machine.', 'Keep your arms straight.', 'Pull the bar down to your thighs.', 'Squeeze your lats hard.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_back_13', 'name': 'Rack Pulls', 'categoryId': 'cat_back',
          'description': 'A partial deadlift that builds massive upper back and trap thickness.',
          'targetMuscle': 'Upper Back / Traps', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Set the rack pins at knee height.', 'Pull the bar up and stand tall.', 'Squeeze your shoulder blades back.', 'Lower the bar back to the pins.'],
          'duration': '60s', 'sets': 3, 'reps': 8,
        },
        {
          'id': 'ex_back_14', 'name': 'Pendlay Row', 'categoryId': 'cat_back',
          'description': 'A stricter version of the barbell row where the bar starts on the floor every rep.',
          'targetMuscle': 'Mid-Back / Explosiveness', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Start with the bar on the floor.', 'Row the bar explosively to your stomach.', 'Return the bar to the floor.', 'Keep your back parallel to the ground.'],
          'duration': '60s', 'sets': 3, 'reps': 6,
        },
        {
          'id': 'ex_back_15', 'name': 'Renegade Row', 'categoryId': 'cat_back',
          'description': 'Combines a plank with a row for extreme core and back stability.',
          'targetMuscle': 'Back / Core', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Start in a push-up position with dumbbells.', 'Row one weight to your hip while balancing.', 'Keep your hips level.', 'Switch sides.'],
          'duration': '60s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_back_16', 'name': 'Chest Supported Row', 'categoryId': 'cat_back',
          'description': 'Eliminates cheating and lower back strain by supporting your torso.',
          'targetMuscle': 'Mid-Back', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Lie chest-down on an incline bench.', 'Pull dumbbells or a bar toward you.', 'Squeeze your back at the top.', 'Lower slowly.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_back_17', 'name': 'Inverted Row', 'categoryId': 'cat_back',
          'description': 'A great bodyweight alternative to barbell rows.',
          'targetMuscle': 'Mid-Back / Lats', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Set a bar at waist height in a rack.', 'Lie under it and pull your chest to the bar.', 'Keep your body straight like a plank.', 'Control the descent.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_back_18', 'name': 'Good Mornings', 'categoryId': 'cat_back',
          'description': 'Targets the lower back and hamstrings with a hinging motion.',
          'targetMuscle': 'Lower Back / Hamstrings', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Place a barbell on your shoulders.', 'Hinge forward at the hips with slightly bent knees.', 'Go down until your back is parallel to the floor.', 'Rise back up.'],
          'duration': '60s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_back_19', 'name': 'Single Arm Lat Pulldown', 'categoryId': 'cat_back',
          'description': 'Helps fix imbalances and allows for a greater range of motion.',
          'targetMuscle': 'Lats', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Use a single handle on the pulldown machine.', 'Pull the handle down to your side.', 'Focus on the stretch at the top.', 'Repeat for the other side.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_back_20', 'name': 'Meadows Row', 'categoryId': 'cat_back',
          'description': 'A landmine rowing variation named after John Meadows for targeting the lats.',
          'targetMuscle': 'Lower Lats', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Stand perpendicular to a landmine barbell.', 'Grip the thick end of the bar.', 'Row the bar to your hip.', 'Focus on a deep stretch.'],
          'duration': '60s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_back_21', 'name': 'V-Bar Pulldown', 'categoryId': 'cat_back',
          'description': 'Uses a narrow grip to maximize lat contraction.',
          'targetMuscle': 'Lats', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Attach a V-bar.', 'Pull the handle to your chest.', 'Lean back slightly.', 'Hold the squeeze at the bottom.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },

        // BICEP (cat_bicep) - 21 exercises
        {
          'id': 'ex_bicep_1', 'name': 'Barbell Bicep Curls', 'categoryId': 'cat_bicep',
          'description': 'The classic mass builder for the biceps.',
          'targetMuscle': 'Biceps Brachii', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Stand tall and hold the bar with an underhand grip.', 'Curl the bar toward your shoulders.', 'Keep your elbows tucked at your sides.', 'Lower with control.'],
          'duration': '45s', 'sets': 4, 'reps': 10,
        },
        {
          'id': 'ex_bicep_2', 'name': 'Dumbbell Alternating Curls', 'categoryId': 'cat_bicep',
          'description': 'Allows for a more natural wrist rotation (supination).',
          'targetMuscle': 'Biceps Brachii', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hold dumbbells at your sides.', 'Curl one weight up while rotating your palm upward.', 'Squeeze at the top.', 'Alternate arms.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_bicep_3', 'name': 'Hammer Curls', 'categoryId': 'cat_bicep',
          'description': 'Builds the brachialis and brachioradialis for thicker arms.',
          'targetMuscle': 'Brachialis / Forearms', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hold dumbbells with palms facing your body.', 'Curl the weights up while keeping palms facing in.', 'Focus on the outer bicep.', 'Lower slowly.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_bicep_4', 'name': 'Preacher Curls (EZ Bar)', 'categoryId': 'cat_bicep',
          'description': 'Isolates the biceps by preventing any momentum or shoulder use.',
          'targetMuscle': 'Short Head of Biceps', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Sit at a preacher bench.', 'Extend your arms fully over the pad.', 'Curl the bar up toward your face.', 'Avoid lifting your elbows off the pad.'],
          'duration': '45s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_bicep_5', 'name': 'Incline Dumbbell Curls', 'categoryId': 'cat_bicep',
          'description': 'Puts the biceps in a stretched position for maximum growth stimulation.',
          'targetMuscle': 'Long Head of Biceps', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Lie on an incline bench.', 'Let your arms hang straight down.', 'Curl the dumbbells up without moving your elbows forward.', 'Feel the deep stretch at the bottom.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_bicep_6', 'name': 'Concentration Curls', 'categoryId': 'cat_bicep',
          'description': 'Classic Arnold-style exercise to build the bicep "peak".',
          'targetMuscle': 'Bicep Peak', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Sit on a bench and lean forward.', 'Brace your elbow against your inner thigh.', 'Curl the weight up slowly.', 'Focus on the mind-muscle connection.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_bicep_7', 'name': 'Cable Curls (Straight Bar)', 'categoryId': 'cat_bicep',
          'description': 'Provides constant tension throughout the entire range of motion.',
          'targetMuscle': 'Biceps', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hold the low cable bar.', 'Curl toward your shoulders.', 'Keep your posture upright.', 'Squeeze hard at the top.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_bicep_8', 'name': 'Cable Curls (Rope)', 'categoryId': 'cat_bicep',
          'description': 'Great for neutral grip curls with constant cable tension.',
          'targetMuscle': 'Brachialis / Biceps', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Attach a rope to the low pulley.', 'Curl the rope up and pull the ends apart at the top.', 'Lower slowly.', 'Maintain tension.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_bicep_9', 'name': 'EZ-Bar Curls', 'categoryId': 'cat_bicep',
          'description': 'The cambered bar reduces wrist strain compared to a straight bar.',
          'targetMuscle': 'Biceps', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hold the EZ-bar on the outer handles.', 'Curl with a standard motion.', 'Keep elbows pinned.', 'Full range of motion.'],
          'duration': '45s', 'sets': 4, 'reps': 10,
        },
        {
          'id': 'ex_bicep_10', 'name': 'Spider Curls', 'categoryId': 'cat_bicep',
          'description': 'Performed on the flat side of a preacher bench to isolate the bicep peak.',
          'targetMuscle': 'Bicep Peak', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Lie chest-down on an incline bench.', 'Let your arms hang straight down.', 'Curl the weights toward your head.', 'Squeeze hard.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_bicep_11', 'name': 'Zottman Curls', 'categoryId': 'cat_bicep',
          'description': 'Combines a regular curl and a reverse curl for total arm development.',
          'targetMuscle': 'Biceps / Forearms', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Curl the dumbbells up with an underhand grip.', 'At the top, rotate your palms to an overhand grip.', 'Lower the weights slowly with the overhand grip.', 'Rotate back at the bottom.'],
          'duration': '45s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_bicep_12', 'name': '21s (Bicep Curls)', 'categoryId': 'cat_bicep',
          'description': 'A high-intensity technique using partial and full reps.',
          'targetMuscle': 'Biceps (Total)', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['7 reps from bottom to mid-way.', '7 reps from mid-way to top.', '7 full range of motion reps.', 'Expect a massive pump.'],
          'duration': '60s', 'sets': 3, 'reps': 21,
        },
        {
          'id': 'ex_bicep_13', 'name': 'Drag Curls', 'categoryId': 'cat_bicep',
          'description': 'Keeps the bar close to the body to minimize shoulder involvement.',
          'targetMuscle': 'Outer Bicep Head', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Pull the bar up your torso by driving your elbows back.', 'Squeeze your biceps at the top.', 'Lower by sliding the bar down your body.', 'Maintain a vertical torso.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_bicep_14', 'name': 'Reverse Curls (Barbell)', 'categoryId': 'cat_bicep',
          'description': 'Targets the brachioradialis and forearm muscles.',
          'targetMuscle': 'Forearms / Biceps', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Grip the bar with an overhand grip.', 'Curl the bar toward your shoulders.', 'Keep your wrists straight.', 'Control the descent.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_bicep_15', 'name': 'Single Arm Cable Curl', 'categoryId': 'cat_bicep',
          'description': 'Isolation exercise to focus on one arm at a time.',
          'targetMuscle': 'Biceps', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Stand next to the cable machine.', 'Curl the handle with one arm.', 'Focus on the peak contraction.', 'Switch arms.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_bicep_16', 'name': 'Bayesian Curls', 'categoryId': 'cat_bicep',
          'description': 'A cable curl performed facing away from the machine for a massive stretch.',
          'targetMuscle': 'Long Head of Biceps', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Face away from the cable machine.', 'Let your arm stretch back behind you.', 'Curl the handle forward.', 'Keep your elbow back.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_bicep_17', 'name': 'High Cable Curls', 'categoryId': 'cat_bicep',
          'description': 'The "Front Double Bicep" pose exercise.',
          'targetMuscle': 'Bicep Peak', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Stand between two high cables.', 'Curl both handles toward your ears.', 'Hold the squeeze for a second.', 'Slowly return.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_bicep_18', 'name': 'Plate Curls', 'categoryId': 'cat_bicep',
          'description': 'Improves grip strength while building bicep mass.',
          'targetMuscle': 'Biceps / Grip', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hold a weight plate by the edges.', 'Curl the plate toward your chin.', 'Keep your elbows tucked.', 'Squeeze hard.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_bicep_19', 'name': 'Waiter Curls', 'categoryId': 'cat_bicep',
          'description': 'Holding a dumbbell like a tray to isolate the bicep peak.',
          'targetMuscle': 'Bicep Peak', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Hold the top end of a dumbbell with both palms facing up.', 'Curl it toward your chin.', 'Keep your elbows forward.', 'Focus on the peak.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_bicep_20', 'name': 'Concentration Cable Curls', 'categoryId': 'cat_bicep',
          'description': 'Cable version of concentration curls for constant tension.',
          'targetMuscle': 'Bicep Peak', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Sit and use a low cable.', 'Rest your arm against your thigh.', 'Curl with control.', 'Maintain tension throughout.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_bicep_21', 'name': 'Cross Body Hammer Curls', 'categoryId': 'cat_bicep',
          'description': 'Targets the brachialis from a different angle.',
          'targetMuscle': 'Brachialis', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Curl the dumbbell across your body toward the opposite shoulder.', 'Keep the neutral grip.', 'Lower slowly.', 'Alternate sides.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },

        // TRICEP (cat_tricep) - 21 exercises
        {
          'id': 'ex_tricep_1', 'name': 'Tricep Pushdowns (Rope)', 'categoryId': 'cat_tricep',
          'description': 'The best isolation exercise for the lateral and medial tricep heads.',
          'targetMuscle': 'Triceps (Lateral Head)', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Grip the rope and pull it down.', 'Separate the rope ends at the bottom.', 'Squeeze your triceps hard.', 'Control the return up.'],
          'duration': '45s', 'sets': 4, 'reps': 15,
        },
        {
          'id': 'ex_tricep_2', 'name': 'Tricep Pushdowns (Straight Bar)', 'categoryId': 'cat_tricep',
          'description': 'Allows for heavier weight than the rope variation.',
          'targetMuscle': 'Triceps (Medial Head)', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Push the bar down to your thighs.', 'Keep your elbows pinned to your sides.', 'Maintain a slight forward lean.', 'Full lockout at the bottom.'],
          'duration': '45s', 'sets': 4, 'reps': 12,
        },
        {
          'id': 'ex_tricep_3', 'name': 'Skull Crushers (EZ Bar)', 'categoryId': 'cat_tricep',
          'description': 'The king of tricep mass builders.',
          'targetMuscle': 'Triceps (Long Head)', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Lie on a bench and hold the bar above your forehead.', 'Lower the bar slowly toward your head.', 'Press back up to the starting position.', 'Keep your elbows tucked.'],
          'duration': '60s', 'sets': 4, 'reps': 10,
        },
        {
          'id': 'ex_tricep_4', 'name': 'Overhead Dumbbell Extension', 'categoryId': 'cat_tricep',
          'description': 'Great for stretching and growing the long head of the triceps.',
          'targetMuscle': 'Triceps (Long Head)', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Hold a dumbbell overhead with both hands.', 'Lower it behind your neck.', 'Press it back up until arms are straight.', 'Keep your core tight.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_tricep_5', 'name': 'Dips (Parallel Bars)', 'categoryId': 'cat_tricep',
          'description': 'A powerful compound movement for overall tricep size.',
          'targetMuscle': 'Triceps (Total)', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Hold yourself up on parallel bars.', 'Lower your body while keeping your torso upright.', 'Push back up until arms are locked.', 'Avoid excessive forward lean.'],
          'duration': '60s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_tricep_6', 'name': 'Bench Dips', 'categoryId': 'cat_tricep',
          'description': 'A great beginner tricep exercise that can be done anywhere.',
          'targetMuscle': 'Triceps', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Place your hands on the edge of a bench.', 'Lower your hips toward the floor.', 'Push back up.', 'Extend legs to make it harder.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_tricep_7', 'name': 'Close Grip Bench Press', 'categoryId': 'cat_tricep',
          'description': 'Shifts the focus of the bench press from chest to triceps.',
          'targetMuscle': 'Triceps (Total)', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Grip the bar at shoulder width.', 'Lower the bar to your lower chest.', 'Tuck your elbows close to your body.', 'Press back up forcefully.'],
          'duration': '60s', 'sets': 4, 'reps': 8,
        },
        {
          'id': 'ex_tricep_8', 'name': 'Diamond Push-Ups (Tricep Focus)', 'categoryId': 'cat_tricep',
          'description': 'The best bodyweight isolation for triceps.',
          'targetMuscle': 'Triceps', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Form a diamond with your hands on the floor.', 'Lower your chest to the diamond.', 'Push back up while squeezing triceps.', 'Keep your core engaged.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_tricep_9', 'name': 'Tricep Kickbacks (Dumbbell)', 'categoryId': 'cat_tricep',
          'description': 'Isolates the triceps at peak contraction.',
          'targetMuscle': 'Triceps (Lateral Head)', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hinge at the hips and hold a dumbbell.', 'Extend your arm back until it is straight.', 'Squeeze the tricep at the top.', 'Lower with control.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_tricep_10', 'name': 'Tricep Kickbacks (Cable)', 'categoryId': 'cat_tricep',
          'description': 'Better than dumbbells because it provides constant tension.',
          'targetMuscle': 'Triceps (Peak)', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Use a low cable without a handle.', 'Extend your arm back.', 'Maintain a horizontal upper arm.', 'Control the weight back.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_tricep_11', 'name': 'French Press', 'categoryId': 'cat_tricep',
          'description': 'A seated version of skull crushers focusing on the stretch.',
          'targetMuscle': 'Triceps (Long Head)', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Sit and hold an EZ bar overhead.', 'Lower the bar behind your head.', 'Keep your elbows pointed forward.', 'Press back up.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_tricep_12', 'name': 'Overhead Cable Extension', 'categoryId': 'cat_tricep',
          'description': 'Constant tension in the stretched position.',
          'targetMuscle': 'Triceps (Long Head)', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Use a rope attachment and face away from the machine.', 'Lean forward and extend your arms.', 'Feel the stretch at the bottom.', 'Squeeze at the top.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_tricep_13', 'name': 'Single Arm Tricep Pushdown', 'categoryId': 'cat_tricep',
          'description': 'Great for fixing imbalances and focusing on the squeeze.',
          'targetMuscle': 'Triceps', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Use a single handle.', 'Push down until lockout.', 'Hold the contraction.', 'Switch arms.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_tricep_14', 'name': 'JM Press', 'categoryId': 'cat_tricep',
          'description': 'A hybrid between a bench press and a skull crusher.',
          'targetMuscle': 'Triceps (Total)', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Lower the bar toward your chin/neck.', 'Roll your elbows forward.', 'Press back up.', 'Keep it controlled.'],
          'duration': '60s', 'sets': 3, 'reps': 8,
        },
        {
          'id': 'ex_tricep_15', 'name': 'Tate Press', 'categoryId': 'cat_tricep',
          'description': 'Targets the medial and lateral heads with a unique movement.',
          'targetMuscle': 'Triceps', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Lie on a bench with dumbbells.', 'Touch the ends of the dumbbells to your chest.', 'Press them up while keeping them together.', 'Focus on the lockout.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_tricep_16', 'name': 'Smith Machine Close Grip Press', 'categoryId': 'cat_tricep',
          'description': 'A stable way to build tricep pressing power.',
          'targetMuscle': 'Triceps', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Position yourself under the Smith bar.', 'Use a narrow grip.', 'Press as you would a bench press.', 'Maintain control.'],
          'duration': '60s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_tricep_17', 'name': 'Reverse Grip Pushdown', 'categoryId': 'cat_tricep',
          'description': 'Underhand grip targets the triceps differently.',
          'targetMuscle': 'Triceps (Medial Head)', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Grip the bar with an underhand grip.', 'Push down to your thighs.', 'Keep elbows pinned.', 'Feel the medial head work.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_tricep_18', 'name': 'Cable Overhead Extension (Single Arm)', 'categoryId': 'cat_tricep',
          'description': 'Isolates the long head with unilateral focus.',
          'targetMuscle': 'Triceps (Long Head)', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Hold a single handle overhead.', 'Extend your arm straight up.', 'Control the descent behind your head.', 'Switch arms.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_tricep_19', 'name': 'Dumbbell Floor Press (Close Grip)', 'categoryId': 'cat_tricep',
          'description': 'Excellent for tricep power without shoulder strain.',
          'targetMuscle': 'Triceps', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Lie on the floor with dumbbells.', 'Keep palms facing each other.', 'Lower until elbows touch the floor.', 'Press up.'],
          'duration': '60s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_tricep_20', 'name': 'Cross-Body Cable Extension', 'categoryId': 'cat_tricep',
          'description': 'Targets the lateral head by pulling across the body.',
          'targetMuscle': 'Lateral Head', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Stand sideways to the machine.', 'Pull the cable across your body.', 'Lock out your arm.', 'Maintain tension.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_tricep_21', 'name': 'Tricep Push-Ups', 'categoryId': 'cat_tricep',
          'description': 'Standard push-ups with hands closer to isolate triceps.',
          'targetMuscle': 'Triceps', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Place hands under shoulders.', 'Keep elbows tucked to your ribs.', 'Lower and push up.', 'Focus on tricep extension.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },

        // SHOULDERS (cat_shoulders) - 21 exercises
        {
          'id': 'ex_shoulders_1', 'name': 'Overhead Press (Barbell)', 'categoryId': 'cat_shoulders',
          'description': 'The fundamental compound movement for boulder shoulders.',
          'targetMuscle': 'Front Deltoids', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Stand tall with the bar on your upper chest.', 'Press the bar straight overhead.', 'Keep your core tight and don\'t arch your back.', 'Lower with control.'],
          'duration': '60s', 'sets': 4, 'reps': 8,
        },
        {
          'id': 'ex_shoulders_2', 'name': 'Dumbbell Shoulder Press', 'categoryId': 'cat_shoulders',
          'description': 'Allows for a greater range of motion and unilateral stability.',
          'targetMuscle': 'Shoulders (Total)', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Sit or stand holding dumbbells at shoulder height.', 'Press the weights up until arms are extended.', 'Lower them slowly to ear level.', 'Keep elbows slightly forward.'],
          'duration': '60s', 'sets': 4, 'reps': 10,
        },
        {
          'id': 'ex_shoulders_3', 'name': 'Lateral Raises (Dumbbell)', 'categoryId': 'cat_shoulders',
          'description': 'The best exercise for building the "width" of the shoulders.',
          'targetMuscle': 'Side Deltoids', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hold dumbbells at your sides.', 'Raise them out to the side until level with shoulders.', 'Lower them slowly.', 'Don\'t swing the weights.'],
          'duration': '45s', 'sets': 4, 'reps': 15,
        },
        {
          'id': 'ex_shoulders_4', 'name': 'Lateral Raises (Cable)', 'categoryId': 'cat_shoulders',
          'description': 'Constant tension on the side delts for better hypertrophy.',
          'targetMuscle': 'Side Deltoids', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Use a low cable handle.', 'Pull the cable out to your side.', 'Maintain a slight bend in your elbow.', 'Control the descent.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_shoulders_5', 'name': 'Front Raises (Dumbbell)', 'categoryId': 'cat_shoulders',
          'description': 'Isolates the front deltoids for better definition.',
          'targetMuscle': 'Front Deltoids', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hold dumbbells in front of your thighs.', 'Raise them straight out in front to shoulder height.', 'Lower slowly.', 'Alternate arms if preferred.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_shoulders_6', 'name': 'Front Raises (Plate)', 'categoryId': 'cat_shoulders',
          'description': 'A stable way to isolate front delts using a single weight plate.',
          'targetMuscle': 'Front Deltoids', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hold a plate at 3 and 9 o\'clock.', 'Raise it to eye level.', 'Hold for a second.', 'Lower with control.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_shoulders_7', 'name': 'Rear Delt Flyes (Dumbbell)', 'categoryId': 'cat_shoulders',
          'description': 'Builds the back of the shoulder for a 3D look.',
          'targetMuscle': 'Rear Deltoids', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Hinge at the hips until your torso is nearly horizontal.', 'Raise the dumbbells out to the sides.', 'Squeeze your rear delts at the top.', 'Lower slowly.'],
          'duration': '45s', 'sets': 4, 'reps': 15,
        },
        {
          'id': 'ex_shoulders_8', 'name': 'Rear Delt Flyes (Machine)', 'categoryId': 'cat_shoulders',
          'description': 'Isolates the rear delts with a guided, safe path.',
          'targetMuscle': 'Rear Deltoids', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Sit facing the machine pad.', 'Push the handles back and out.', 'Squeeze your rear delts.', 'Control the weight back forward.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_shoulders_9', 'name': 'Face Pulls (Shoulder Health)', 'categoryId': 'cat_shoulders',
          'description': 'Essential for shoulder longevity and rear delt growth.',
          'targetMuscle': 'Rear Deltoids / Rotator Cuff', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Pull the rope toward your forehead.', 'Flare your elbows out and back.', 'Focus on the "W" shape at the top.', 'Hold the squeeze.'],
          'duration': '45s', 'sets': 3, 'reps': 20,
        },
        {
          'id': 'ex_shoulders_10', 'name': 'Arnold Press', 'categoryId': 'cat_shoulders',
          'description': 'A unique pressing motion that hits all three shoulder heads.',
          'targetMuscle': 'Shoulders (Total)', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Start with dumbbells in front of your face, palms facing you.', 'Rotate your palms as you press the weights up.', 'Reverse the motion on the way down.', 'Keep it smooth.'],
          'duration': '60s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_shoulders_11', 'name': 'Upright Row (Barbell)', 'categoryId': 'cat_shoulders',
          'description': 'Builds side delts and upper traps.',
          'targetMuscle': 'Side Deltoids / Traps', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Hold the bar with a slightly wider than shoulder grip.', 'Pull the bar up toward your chin.', 'Keep the bar close to your body.', 'Lower with control.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_shoulders_12', 'name': 'Upright Row (Dumbbell)', 'categoryId': 'cat_shoulders',
          'description': 'Often safer for the wrists than the barbell version.',
          'targetMuscle': 'Shoulders / Traps', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Pull dumbbells up to your chest level.', 'Keep your elbows above your hands.', 'Lower slowly.', 'Focus on the delts.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_shoulders_13', 'name': 'Shrugs (Barbell)', 'categoryId': 'cat_shoulders',
          'description': 'The best way to build massive upper traps.',
          'targetMuscle': 'Traps (Upper)', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hold a heavy bar in front of you.', 'Shrug your shoulders toward your ears.', 'Hold the squeeze at the top.', 'Lower without rolling your shoulders.'],
          'duration': '45s', 'sets': 4, 'reps': 12,
        },
        {
          'id': 'ex_shoulders_14', 'name': 'Shrugs (Dumbbell)', 'categoryId': 'cat_shoulders',
          'description': 'Allows for a more natural arm position for trap building.',
          'targetMuscle': 'Traps', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hold dumbbells at your sides.', 'Lift your shoulders as high as possible.', 'Lower slowly.', 'Keep your neck neutral.'],
          'duration': '45s', 'sets': 4, 'reps': 15,
        },
        {
          'id': 'ex_shoulders_15', 'name': 'Push Press', 'categoryId': 'cat_shoulders',
          'description': 'Uses leg drive to press heavier weights overhead.',
          'targetMuscle': 'Shoulders / Power', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Dip your knees slightly.', 'Explode up through your legs.', 'Press the bar overhead.', 'Control the descent back to your chest.'],
          'duration': '60s', 'sets': 3, 'reps': 5,
        },
        {
          'id': 'ex_shoulders_16', 'name': 'Smith Machine Shoulder Press', 'categoryId': 'cat_shoulders',
          'description': 'Focuses on the shoulders without stabilization requirements.',
          'targetMuscle': 'Front Deltoids', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Sit and press the bar overhead.', 'Control the weight to your chin.', 'Explode back up.', 'Safe and effective.'],
          'duration': '60s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_shoulders_17', 'name': 'Landmine Shoulder Press', 'categoryId': 'cat_shoulders',
          'description': 'A shoulder-friendly pressing alternative.',
          'targetMuscle': 'Shoulders', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Hold the bar at shoulder height.', 'Press up and forward.', 'Keep your core engaged.', 'Control the weight back down.'],
          'duration': '60s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_shoulders_18', 'name': 'Single Arm Landmine Press', 'categoryId': 'cat_shoulders',
          'description': 'Adds a core stability component to the landmine press.',
          'targetMuscle': 'Shoulders / Core', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Press with one arm at a time.', 'Stabilize with your core.', 'Full extension.', 'Switch sides.'],
          'duration': '60s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_shoulders_19', 'name': 'Bradford Press', 'categoryId': 'cat_shoulders',
          'description': 'An old-school burner that hits the front and mid delts.',
          'targetMuscle': 'Shoulders (Burner)', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Press the bar just over your head.', 'Lower it behind your neck.', 'Press it just over your head again.', 'Lower to the front. Repeat without locking out.'],
          'duration': '60s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_shoulders_20', 'name': 'Lu Raises', 'categoryId': 'cat_shoulders',
          'description': 'Full range of motion lateral raises for complete shoulder health.',
          'targetMuscle': 'Side Deltoids / Mobility', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Raise dumbbells all the way until they meet overhead.', 'Rotate your palms as you go.', 'Lower with full control.', 'Focus on the entire arc.'],
          'duration': '60s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_shoulders_21', 'name': 'Bus Drivers', 'categoryId': 'cat_shoulders',
          'description': 'A high-rep finisher for the front delts.',
          'targetMuscle': 'Front Deltoids', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hold a weight plate straight out in front of you.', 'Rotate it left and right like a steering wheel.', 'Keep your arms straight.', 'Feel the burn.'],
          'duration': '45s', 'sets': 3, 'reps': 30,
        },

        // FOREARMS (cat_forearms) - 21 exercises
        {
          'id': 'ex_forearms_1', 'name': 'Barbell Wrist Curls', 'categoryId': 'cat_forearms',
          'description': 'The fundamental movement for building the forearm flexors.',
          'targetMuscle': 'Forearm Flexors', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Rest your forearms on a bench holding a bar.', 'Curl your wrists upward.', 'Lower the bar to your fingertips.', 'Squeeze at the top.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_forearms_2', 'name': 'Reverse Barbell Wrist Curls', 'categoryId': 'cat_forearms',
          'description': 'Builds the top of the forearm and improves wrist stability.',
          'targetMuscle': 'Forearm Extensors', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hold the bar with an overhand grip.', 'Curl your wrists upward.', 'Lower with control.', 'Keep your forearms supported.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_forearms_3', 'name': 'Dumbbell Wrist Curls', 'categoryId': 'cat_forearms',
          'description': 'Allows for individual wrist focus and better range of motion.',
          'targetMuscle': 'Forearm Flexors', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Curl the dumbbell using only your wrist.', 'Control the descent.', 'Squeeze the forearm.', 'Switch arms.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_forearms_4', 'name': 'Reverse Dumbbell Wrist Curls', 'categoryId': 'cat_forearms',
          'description': 'Isolates the extensors with dumbbells.',
          'targetMuscle': 'Forearm Extensors', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Use an overhand grip with a dumbbell.', 'Extend the wrist upward.', 'Slowly lower.', 'Maintain a stable forearm.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_forearms_5', 'name': 'Hammer Curls (Forearm Focus)', 'categoryId': 'cat_forearms',
          'description': 'Builds the thick brachioradialis muscle.',
          'targetMuscle': 'Brachioradialis', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hold dumbbells with a neutral grip.', 'Curl as usual.', 'Focus on the forearm squeeze.', 'Control the weight.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_forearms_6', 'name': 'Reverse Barbell Curls', 'categoryId': 'cat_forearms',
          'description': 'A great movement for building both biceps and forearms.',
          'targetMuscle': 'Forearms / Biceps', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Use an overhand grip on the bar.', 'Curl the bar toward your shoulders.', 'Keep your wrists locked.', 'Slow descent.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_forearms_7', 'name': 'Farmers Walk', 'categoryId': 'cat_forearms',
          'description': 'Functional strength movement for extreme grip endurance.',
          'targetMuscle': 'Grip / Forearms', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hold heavy dumbbells or kettlebells.', 'Walk for a set distance or time.', 'Keep your chest up and shoulders back.', 'Don\'t drop the weights.'],
          'duration': '60s', 'sets': 3, 'reps': 1,
        },
        {
          'id': 'ex_forearms_8', 'name': 'Plate Pinch', 'categoryId': 'cat_forearms',
          'description': 'Develops finger and thumb strength.',
          'targetMuscle': 'Grip / Fingers', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hold two smooth plates together by pinching them with your fingers.', 'Hold for as long as possible.', 'Keep your arms straight.', 'Keep your core tight.'],
          'duration': '60s', 'sets': 3, 'reps': 1,
        },
        {
          'id': 'ex_forearms_9', 'name': 'Wrist Roller', 'categoryId': 'cat_forearms',
          'description': 'One of the most intense forearm finishers.',
          'targetMuscle': 'Forearms (Total)', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Hold the roller with arms extended.', 'Roll the weight up by rotating your wrists.', 'Roll it back down with control.', 'Keep your arms straight.'],
          'duration': '60s', 'sets': 3, 'reps': 2,
        },
        {
          'id': 'ex_forearms_10', 'name': 'Behind the Back Wrist Curls', 'categoryId': 'cat_forearms',
          'description': 'A unique angle for targeting the forearm flexors.',
          'targetMuscle': 'Forearm Flexors', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Hold a bar behind your back.', 'Curl your wrists upward.', 'Hold the squeeze.', 'Lower slowly.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_forearms_11', 'name': 'Towel Pull-Ups', 'categoryId': 'cat_forearms',
          'description': 'Extreme grip challenge by using a towel instead of a bar.',
          'targetMuscle': 'Grip / Forearms', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Drape two towels over a pull-up bar.', 'Grip the towels and perform pull-ups.', 'Squeeze the towels as hard as possible.', 'Maintain control.'],
          'duration': '60s', 'sets': 3, 'reps': 5,
        },
        {
          'id': 'ex_forearms_12', 'name': 'Dead Hangs', 'categoryId': 'cat_forearms',
          'description': 'Simple but effective for building elite grip strength.',
          'targetMuscle': 'Grip Strength', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hang from a pull-up bar for as long as possible.', 'Keep your shoulders engaged.', 'Don\'t let your grip slip.', 'Time yourself.'],
          'duration': '60s', 'sets': 3, 'reps': 1,
        },
        {
          'id': 'ex_forearms_13', 'name': 'Fat Grip Curls', 'categoryId': 'cat_forearms',
          'description': 'Increases forearm activation by making the handle thicker.',
          'targetMuscle': 'Forearms / Biceps', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Use fat grips on dumbbells or a bar.', 'Perform curls as usual.', 'Focus on holding the thick grip.', 'Squeeze hard.'],
          'duration': '45s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_forearms_14', 'name': 'Zottman Curls (Forearm Focus)', 'categoryId': 'cat_forearms',
          'description': 'The best "bang for your buck" arm and forearm exercise.',
          'targetMuscle': 'Forearms / Biceps', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Curl up with palms up.', 'Rotate to palms down at the top.', 'Lower slowly with palms down.', 'Control the weight.'],
          'duration': '45s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_forearms_15', 'name': 'Cable Wrist Curls', 'categoryId': 'cat_forearms',
          'description': 'Provides constant tension for better forearm pumps.',
          'targetMuscle': 'Forearm Flexors', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Use a low cable bar.', 'Curl your wrists upward.', 'Maintain a slow tempo.', 'Full range of motion.'],
          'duration': '45s', 'sets': 3, 'reps': 20,
        },
        {
          'id': 'ex_forearms_16', 'name': 'Reverse Cable Curls', 'categoryId': 'cat_forearms',
          'description': 'Constant tension on the extensors and brachioradialis.',
          'targetMuscle': 'Forearms', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Use a low cable with an overhand grip.', 'Curl up smoothly.', 'Focus on the forearm burn.', 'Control the return.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_forearms_17', 'name': 'Single Arm Wrist Curl (Dumbbell)', 'categoryId': 'cat_forearms',
          'description': 'Focus on one forearm at a time for maximum isolation.',
          'targetMuscle': 'Forearms', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Support your arm on your leg.', 'Perform wrist curls.', 'Slow and controlled reps.', 'Switch arms.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_forearms_18', 'name': 'Kettlebell Bottom-Up Press', 'categoryId': 'cat_forearms',
          'description': 'Requires extreme grip and forearm stability.',
          'targetMuscle': 'Forearm Stability / Grip', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Hold a kettlebell upside down.', 'Press it overhead while keeping it balanced.', 'Squeeze the handle hard.', 'Maintain focus.'],
          'duration': '60s', 'sets': 3, 'reps': 8,
        },
        {
          'id': 'ex_forearms_19', 'name': 'Grip Crushers', 'categoryId': 'cat_forearms',
          'description': 'Uses specialized tools to build crushing power.',
          'targetMuscle': 'Crushing Grip', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Squeeze the hand gripper until the handles touch.', 'Hold for a second.', 'Slowly release.', 'Repeat.'],
          'duration': '30s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_forearms_20', 'name': 'Finger Curls', 'categoryId': 'cat_forearms',
          'description': 'Builds the muscles that control finger movement.',
          'targetMuscle': 'Finger Flexors', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hold a bar with your fingertips.', 'Curl it up into your palms.', 'Squeeze hard.', 'Lower back to fingertips.'],
          'duration': '45s', 'sets': 3, 'reps': 20,
        },
        {
          'id': 'ex_forearms_21', 'name': 'Hand Grippers', 'categoryId': 'cat_forearms',
          'description': 'The classic tool for building a vice-like grip.',
          'targetMuscle': 'Grip', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Squeeze as hard as possible.', 'Hold the contraction.', 'Controlled release.', 'Consistent practice is key.'],
          'duration': '30s', 'sets': 3, 'reps': 15,
        },

        // CARDIO (cat_cardio) - 21 exercises
        {
          'id': 'ex_cardio_1', 'name': 'Treadmill Running', 'categoryId': 'cat_cardio',
          'description': 'The standard for cardiovascular endurance and calorie burning.',
          'targetMuscle': 'Heart / Legs', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Set a comfortable pace.', 'Maintain upright posture.', 'Breathe rhythmically.', 'Cool down slowly.'],
          'duration': '20m', 'sets': 1, 'reps': 1,
        },
        {
          'id': 'ex_cardio_2', 'name': 'Stationary Bike', 'categoryId': 'cat_cardio',
          'description': 'Low impact cardio great for recovery or intensity.',
          'targetMuscle': 'Quads / Heart', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Adjust seat height.', 'Pedal at a consistent RPM.', 'Increase resistance for intensity.', 'Keep your core engaged.'],
          'duration': '15m', 'sets': 1, 'reps': 1,
        },
        {
          'id': 'ex_cardio_3', 'name': 'Elliptical Trainer', 'categoryId': 'cat_cardio',
          'description': 'Full body cardio with minimal joint impact.',
          'targetMuscle': 'Full Body / Heart', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Move in a smooth circular motion.', 'Use the handles for upper body work.', 'Maintain a steady pace.', 'Keep your feet flat.'],
          'duration': '15m', 'sets': 1, 'reps': 1,
        },
        {
          'id': 'ex_cardio_4', 'name': 'Rowing Machine', 'categoryId': 'cat_cardio',
          'description': 'The best full-body cardio machine for power and endurance.',
          'targetMuscle': 'Back / Legs / Heart', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Push with your legs first.', 'Lean back slightly and pull the handle.', 'Return arms, then hinge, then bend knees.', 'Keep a rhythmic stroke.'],
          'duration': '10m', 'sets': 1, 'reps': 1,
        },
        {
          'id': 'ex_cardio_5', 'name': 'Jump Rope', 'categoryId': 'cat_cardio',
          'description': 'High intensity cardio that improves coordination.',
          'targetMuscle': 'Calves / Heart', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Jump on the balls of your feet.', 'Use your wrists to turn the rope.', 'Keep jumps low to the ground.', 'Find a steady rhythm.'],
          'duration': '5m', 'sets': 3, 'reps': 1,
        },
        {
          'id': 'ex_cardio_6', 'name': 'Burpees', 'categoryId': 'cat_cardio',
          'description': 'The ultimate bodyweight cardio and strength hybrid.',
          'targetMuscle': 'Full Body / Heart', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Drop into a squat.', 'Kick feet back into a plank.', 'Perform a push-up.', 'Jump back forward and explode upward.'],
          'duration': '60s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_cardio_7', 'name': 'Mountain Climbers', 'categoryId': 'cat_cardio',
          'description': 'Builds core strength while elevating the heart rate.',
          'targetMuscle': 'Core / Heart', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Start in a plank position.', 'Drive one knee toward your chest.', 'Quickly switch legs.', 'Keep your back flat.'],
          'duration': '45s', 'sets': 3, 'reps': 30,
        },
        {
          'id': 'ex_cardio_8', 'name': 'Jumping Jacks', 'categoryId': 'cat_cardio',
          'description': 'Classic warm-up or cardio movement.',
          'targetMuscle': 'Full Body', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Jump and spread legs while clapping hands overhead.', 'Jump back to starting position.', 'Maintain a fast pace.', 'Keep arms straight.'],
          'duration': '60s', 'sets': 3, 'reps': 50,
        },
        {
          'id': 'ex_cardio_9', 'name': 'High Knees', 'categoryId': 'cat_cardio',
          'description': 'Running in place with an emphasis on knee height.',
          'targetMuscle': 'Hip Flexors / Heart', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Bring your knees up to waist height.', 'Move your arms as if running.', 'Stay on the balls of your feet.', 'Pump quickly.'],
          'duration': '45s', 'sets': 3, 'reps': 40,
        },
        {
          'id': 'ex_cardio_10', 'name': 'Box Jumps', 'categoryId': 'cat_cardio',
          'description': 'Explosive cardio that builds leg power.',
          'targetMuscle': 'Legs / Heart', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Stand in front of a sturdy box.', 'Jump up and land softly on the box.', 'Stand up fully.', 'Step down carefully.'],
          'duration': '60s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_cardio_11', 'name': 'Stair Climber', 'categoryId': 'cat_cardio',
          'description': 'Intense cardio that targets the glutes and legs.',
          'targetMuscle': 'Glutes / Heart', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Maintain a steady climbing pace.', 'Don\'t lean too heavily on the rails.', 'Take full steps.', 'Keep your heart rate up.'],
          'duration': '15m', 'sets': 1, 'reps': 1,
        },
        {
          'id': 'ex_cardio_12', 'name': 'Battle Ropes', 'categoryId': 'cat_cardio',
          'description': 'High intensity upper body cardio.',
          'targetMuscle': 'Arms / Shoulders / Heart', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Hold the rope ends and create waves.', 'Keep a slight bend in your knees.', 'Maintain high intensity.', 'Breathe throughout.'],
          'duration': '30s', 'sets': 5, 'reps': 1,
        },
        {
          'id': 'ex_cardio_13', 'name': 'Kettlebell Swings', 'categoryId': 'cat_cardio',
          'description': 'Builds explosive power and cardio endurance.',
          'targetMuscle': 'Posterior Chain / Heart', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Hinge at the hips.', 'Swing the kettlebell to shoulder height.', 'Snap your hips forward.', 'Keep your back flat.'],
          'duration': '60s', 'sets': 3, 'reps': 20,
        },
        {
          'id': 'ex_cardio_14', 'name': 'Assault Bike', 'categoryId': 'cat_cardio',
          'description': 'The most grueling cardio machine for interval training.',
          'targetMuscle': 'Full Body / Heart', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Pedal and push/pull the handles simultaneously.', 'Maintain max effort for intervals.', 'Breathe hard.', 'Expect total fatigue.'],
          'duration': '10m', 'sets': 1, 'reps': 1,
        },
        {
          'id': 'ex_cardio_15', 'name': 'Swimming', 'categoryId': 'cat_cardio',
          'description': 'Full body, zero-impact cardio.',
          'targetMuscle': 'Full Body', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Maintain proper stroke form.', 'Breathe consistently.', 'Keep a steady lap pace.', 'Focus on efficiency.'],
          'duration': '30m', 'sets': 1, 'reps': 1,
        },
        {
          'id': 'ex_cardio_16', 'name': 'Sprint Intervals', 'categoryId': 'cat_cardio',
          'description': 'Max effort running for short bursts.',
          'targetMuscle': 'Legs / Heart', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Run at 100% effort.', 'Rest or walk for recovery.', 'Repeat for sets.', 'Proper warm-up is essential.'],
          'duration': '15m', 'sets': 10, 'reps': 1,
        },
        {
          'id': 'ex_cardio_17', 'name': 'Box Steps', 'categoryId': 'cat_cardio',
          'description': 'Lower intensity alternative to box jumps.',
          'targetMuscle': 'Legs', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Step up onto the box.', 'Step back down.', 'Alternate leading legs.', 'Maintain a fast pace.'],
          'duration': '60s', 'sets': 3, 'reps': 30,
        },
        {
          'id': 'ex_cardio_18', 'name': 'Shadow Boxing', 'categoryId': 'cat_cardio',
          'description': 'Improves speed, coordination, and cardio.',
          'targetMuscle': 'Arms / Heart', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Throw punches at the air.', 'Move your feet and head.', 'Stay light on your toes.', 'Keep your hands up.'],
          'duration': '3m', 'sets': 3, 'reps': 1,
        },
        {
          'id': 'ex_cardio_19', 'name': 'Skaters', 'categoryId': 'cat_cardio',
          'description': 'Lateral movement cardio that builds stability.',
          'targetMuscle': 'Glutes / Legs / Heart', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Jump side to side.', 'Land on one foot and sweep the other behind.', 'Swing your arms.', 'Maintain balance.'],
          'duration': '45s', 'sets': 3, 'reps': 30,
        },
        {
          'id': 'ex_cardio_20', 'name': 'Bear Crawls', 'categoryId': 'cat_cardio',
          'description': 'Full body movement that challenges the heart.',
          'targetMuscle': 'Full Body / Core', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Move on all fours with knees off the ground.', 'Keep your back flat.', 'Move quickly.', 'Maintain coordination.'],
          'duration': '60s', 'sets': 3, 'reps': 1,
        },
        {
          'id': 'ex_cardio_21', 'name': 'Plank Jacks', 'categoryId': 'cat_cardio',
          'description': 'Combines a plank with jumping jacks for core and cardio.',
          'targetMuscle': 'Core / Heart', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['In a plank, jump your feet wide and back together.', 'Keep your hips from bouncing.', 'Maintain a fast pace.', 'Core tight.'],
          'duration': '45s', 'sets': 3, 'reps': 30,
        },

        // LEGS (cat_legs) - 21 exercises
        {
          'id': 'ex_legs_1', 'name': 'Barbell Squats', 'categoryId': 'cat_legs',
          'description': 'The fundamental movement for building massive leg strength.',
          'targetMuscle': 'Quads / Glutes', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Place bar on upper traps.', 'Squat down until thighs are parallel to floor.', 'Keep back straight and chest up.', 'Drive back up through heels.'],
          'duration': '90s', 'sets': 4, 'reps': 8,
        },
        {
          'id': 'ex_legs_2', 'name': 'Front Squats', 'categoryId': 'cat_legs',
          'description': 'Targets the quads more heavily and requires a vertical torso.',
          'targetMuscle': 'Quads', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Rest the bar on your front deltoids.', 'Maintain an upright posture.', 'Squat deep.', 'Press back up.'],
          'duration': '60s', 'sets': 3, 'reps': 10,
        },
        {
          'id': 'ex_legs_3', 'name': 'Leg Press', 'categoryId': 'cat_legs',
          'description': 'Allows for heavy loading without spinal compression.',
          'targetMuscle': 'Quads / Glutes', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Place feet shoulder-width on the platform.', 'Lower the weight until knees are at 90 degrees.', 'Press back up without locking knees.', 'Keep your back against the pad.'],
          'duration': '60s', 'sets': 4, 'reps': 12,
        },
        {
          'id': 'ex_legs_4', 'name': 'Leg Extensions', 'categoryId': 'cat_legs',
          'description': 'The best isolation exercise for the quadriceps.',
          'targetMuscle': 'Quadriceps', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Sit and place feet under the pads.', 'Extend legs fully.', 'Squeeze the quads at the top.', 'Lower with control.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_legs_5', 'name': 'Seated Leg Curls', 'categoryId': 'cat_legs',
          'description': 'Isolates the hamstrings with a great stretch.',
          'targetMuscle': 'Hamstrings', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Sit and secure your legs.', 'Curl the pad toward your seat.', 'Squeeze at the bottom.', 'Return slowly.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_legs_6', 'name': 'Lying Leg Curls', 'categoryId': 'cat_legs',
          'description': 'Isolates the hamstrings in a prone position.',
          'targetMuscle': 'Hamstrings', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Lie chest down on the machine.', 'Curl the weight toward your glutes.', 'Keep your hips on the pad.', 'Slow descent.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_legs_7', 'name': 'Romanian Deadlift', 'categoryId': 'cat_legs',
          'description': 'The best movement for building the hamstrings and glutes.',
          'targetMuscle': 'Hamstrings / Glutes', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Hinge at the hips with a slight knee bend.', 'Lower the bar along your legs.', 'Feel the deep stretch in your hamstrings.', 'Rise back up by snapping hips forward.'],
          'duration': '60s', 'sets': 4, 'reps': 10,
        },
        {
          'id': 'ex_legs_8', 'name': 'Stiff Leg Deadlift', 'categoryId': 'cat_legs',
          'description': 'Focuses purely on the hamstrings by minimizing knee bend.',
          'targetMuscle': 'Hamstrings', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Keep legs nearly straight.', 'Lower the bar to the floor.', 'Focus on the hamstring stretch.', 'Stand back up.'],
          'duration': '60s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_legs_9', 'name': 'Walking Lunges', 'categoryId': 'cat_legs',
          'description': 'Great for functional strength and balance.',
          'targetMuscle': 'Quads / Glutes', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Step forward and lower your back knee.', 'Maintain an upright torso.', 'Step forward into the next rep.', 'Keep your core engaged.'],
          'duration': '60s', 'sets': 3, 'reps': 20,
        },
        {
          'id': 'ex_legs_10', 'name': 'Bulgarian Split Squats', 'categoryId': 'cat_legs',
          'description': 'Extremely effective for isolating one leg at a time.',
          'targetMuscle': 'Quads / Glutes', 'difficulty': 'Hard', 'gifUrl': gifUrl,
          'steps': ['Place one foot on a bench behind you.', 'Lower your front leg until thigh is parallel.', 'Keep your chest up.', 'Drive up through the front heel.'],
          'duration': '60s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_legs_11', 'name': 'Goblet Squats', 'categoryId': 'cat_legs',
          'description': 'Excellent beginner squat variation using a dumbbell.',
          'targetMuscle': 'Legs / Core', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Hold a dumbbell at chest height.', 'Squat deep.', 'Keep your elbows inside your knees.', 'Drive back up.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_legs_12', 'name': 'Hack Squats', 'categoryId': 'cat_legs',
          'description': 'Machine squat that places more emphasis on the outer quads.',
          'targetMuscle': 'Quadriceps', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Position yourself in the machine.', 'Lower until knees are at 90 degrees.', 'Press back up.', 'Maintain a stable back.'],
          'duration': '60s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_legs_13', 'name': 'Calf Raises (Standing)', 'categoryId': 'cat_legs',
          'description': 'Builds the gastrocnemius (upper calf).',
          'targetMuscle': 'Calves', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Stand on a platform with heels hanging off.', 'Rise up onto your toes.', 'Hold the squeeze at the top.', 'Lower for a deep stretch.'],
          'duration': '30s', 'sets': 4, 'reps': 20,
        },
        {
          'id': 'ex_legs_14', 'name': 'Calf Raises (Seated)', 'categoryId': 'cat_legs',
          'description': 'Builds the soleus (lower calf).',
          'targetMuscle': 'Lower Calves', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Sit with weight on your knees.', 'Rise up on your toes.', 'Focus on the stretch.', 'Squeeze hard.'],
          'duration': '30s', 'sets': 4, 'reps': 20,
        },
        {
          'id': 'ex_legs_15', 'name': 'Leg Press Calf Raises', 'categoryId': 'cat_legs',
          'description': 'Allows for heavy calf training on the leg press machine.',
          'targetMuscle': 'Calves', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Place toes on the bottom of the platform.', 'Press the platform with your toes.', 'Full stretch and squeeze.', 'Safety first.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_legs_16', 'name': 'Glute Bridges', 'categoryId': 'cat_legs',
          'description': 'Isolates the glutes with minimal leg involvement.',
          'targetMuscle': 'Glutes', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Lie on your back with knees bent.', 'Lift your hips toward the ceiling.', 'Squeeze your glutes at the top.', 'Lower slowly.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_legs_17', 'name': 'Hip Thrusts', 'categoryId': 'cat_legs',
          'description': 'The best movement for overall glute development.',
          'targetMuscle': 'Glutes', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Rest your upper back on a bench.', 'Place a bar over your hips.', 'Drive your hips up.', 'Squeeze hard at the top.'],
          'duration': '60s', 'sets': 4, 'reps': 10,
        },
        {
          'id': 'ex_legs_18', 'name': 'Step-Ups', 'categoryId': 'cat_legs',
          'description': 'Great for glute power and leg balance.',
          'targetMuscle': 'Glutes / Quads', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Step up onto a box.', 'Drive through the lead heel.', 'Stand tall.', 'Step back down with control.'],
          'duration': '45s', 'sets': 3, 'reps': 12,
        },
        {
          'id': 'ex_legs_19', 'name': 'Sumo Squats', 'categoryId': 'cat_legs',
          'description': 'Targets the inner thighs and glutes.',
          'targetMuscle': 'Adductors / Glutes', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Stand with a wide stance, toes pointed out.', 'Squat deep.', 'Keep your chest up.', 'Press back up.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },
        {
          'id': 'ex_legs_20', 'name': 'Box Squats', 'categoryId': 'cat_legs',
          'description': 'Builds explosive power and teaches proper squat depth.',
          'targetMuscle': 'Glutes / Quads', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Squat down until you sit on the box.', 'Pause for a second.', 'Explode back up.', 'Keep your shins vertical.'],
          'duration': '60s', 'sets': 3, 'reps': 8,
        },
        {
          'id': 'ex_legs_21', 'name': 'Curtsy Lunges', 'categoryId': 'cat_legs',
          'description': 'Targets the glute medius for better hip stability.',
          'targetMuscle': 'Glute Medius', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Step one leg back and across the other.', 'Lower into a lunge.', 'Return to start.', 'Switch sides.'],
          'duration': '45s', 'sets': 3, 'reps': 15,
        },

        // STRETCHING (cat_stretching) - 21 exercises
        {
          'id': 'ex_stretching_1', 'name': 'Touching Toes', 'categoryId': 'cat_stretching',
          'description': 'Classic hamstring and lower back stretch.',
          'targetMuscle': 'Hamstrings', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Reach down toward your toes.', 'Keep knees slightly bent if needed.', 'Breathe and sink deeper.', 'Hold for 30s.'],
          'duration': '30s', 'sets': 2, 'reps': 1,
        },
        {
          'id': 'ex_stretching_2', 'name': 'Cobra Stretch', 'categoryId': 'cat_stretching',
          'description': 'Stretches the abdominal muscles and improves spine mobility.',
          'targetMuscle': 'Abdominals / Spine', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Lie on your stomach.', 'Press your upper body up with your hands.', 'Keep your hips on the floor.', 'Look upward.'],
          'duration': '30s', 'sets': 2, 'reps': 1,
        },
        {
          'id': 'ex_stretching_3', 'name': 'Child\'s Pose', 'categoryId': 'cat_stretching',
          'description': 'Relaxes the lower back and shoulders.',
          'targetMuscle': 'Lower Back', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Kneel and sit on your heels.', 'Reach your arms forward on the floor.', 'Rest your forehead on the ground.', 'Breathe deeply.'],
          'duration': '45s', 'sets': 2, 'reps': 1,
        },
        {
          'id': 'ex_stretching_4', 'name': 'Cat-Cow Stretch', 'categoryId': 'cat_stretching',
          'description': 'Improves spinal flexibility and relieves tension.',
          'targetMuscle': 'Spine', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Start on all fours.', 'Arch your back (Cat).', 'Drop your belly and look up (Cow).', 'Move rhythmically.'],
          'duration': '60s', 'sets': 2, 'reps': 10,
        },
        {
          'id': 'ex_stretching_5', 'name': 'Butterfly Stretch', 'categoryId': 'cat_stretching',
          'description': 'Opens the hips and stretches the groin.',
          'targetMuscle': 'Groin / Hips', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Sit with soles of feet together.', 'Gently press knees toward the floor.', 'Lean forward slightly.', 'Keep your back straight.'],
          'duration': '45s', 'sets': 2, 'reps': 1,
        },
        {
          'id': 'ex_stretching_6', 'name': 'Quad Stretch (Standing)', 'categoryId': 'cat_stretching',
          'description': 'Stretches the front of the thigh.',
          'targetMuscle': 'Quadriceps', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Stand on one leg.', 'Pull your other heel toward your glute.', 'Keep your knees together.', 'Maintain balance.'],
          'duration': '30s', 'sets': 2, 'reps': 1,
        },
        {
          'id': 'ex_stretching_7', 'name': 'Pigeon Pose', 'categoryId': 'cat_stretching',
          'description': 'Deep stretch for the glutes and hips.',
          'targetMuscle': 'Glutes', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Bring one knee forward and rotate it out.', 'Extend the other leg back.', 'Lower your torso forward.', 'Focus on the glute stretch.'],
          'duration': '60s', 'sets': 2, 'reps': 1,
        },
        {
          'id': 'ex_stretching_8', 'name': 'Shoulder Stretch (Across Body)', 'categoryId': 'cat_stretching',
          'description': 'Stretches the rear deltoid and upper back.',
          'targetMuscle': 'Shoulders', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Pull one arm across your chest.', 'Hold with the other arm.', 'Keep your shoulder down.', 'Switch sides.'],
          'duration': '30s', 'sets': 2, 'reps': 1,
        },
        {
          'id': 'ex_stretching_9', 'name': 'Tricep Stretch (Overhead)', 'categoryId': 'cat_stretching',
          'description': 'Relieves tension in the triceps.',
          'targetMuscle': 'Triceps', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Reach one arm overhead and bend the elbow.', 'Pull the elbow with the other hand.', 'Reach down your back.', 'Hold.'],
          'duration': '30s', 'sets': 2, 'reps': 1,
        },
        {
          'id': 'ex_stretching_10', 'name': 'Chest Stretch (Against Wall)', 'categoryId': 'cat_stretching',
          'description': 'Opens up the chest after heavy pressing.',
          'targetMuscle': 'Pectorals', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Place one forearm against a wall.', 'Rotate your body away.', 'Feel the stretch in your chest.', 'Switch sides.'],
          'duration': '30s', 'sets': 2, 'reps': 1,
        },
        {
          'id': 'ex_stretching_11', 'name': 'Neck Rotations', 'categoryId': 'cat_stretching',
          'description': 'Relieves neck tension and improves mobility.',
          'targetMuscle': 'Neck', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Slowly rotate your head in a circle.', 'Move gently.', 'Don\'t overextend.', 'Reverse direction.'],
          'duration': '30s', 'sets': 2, 'reps': 5,
        },
        {
          'id': 'ex_stretching_12', 'name': 'Hip Flexor Stretch', 'categoryId': 'cat_stretching',
          'description': 'Targets the psoas and hip flexors.',
          'targetMuscle': 'Hip Flexors', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Kneel on one knee.', 'Push your hips forward.', 'Keep your torso upright.', 'Squeeze the glute of the kneeling leg.'],
          'duration': '45s', 'sets': 2, 'reps': 1,
        },
        {
          'id': 'ex_stretching_13', 'name': 'Calf Stretch (Against Wall)', 'categoryId': 'cat_stretching',
          'description': 'Stretches the gastrocnemius.',
          'targetMuscle': 'Calves', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Press your hands against a wall.', 'Step one leg back and press the heel down.', 'Keep the back leg straight.', 'Switch legs.'],
          'duration': '30s', 'sets': 2, 'reps': 1,
        },
        {
          'id': 'ex_stretching_14', 'name': 'Lat Stretch (Side Bend)', 'categoryId': 'cat_stretching',
          'description': 'Stretches the lats and side of the torso.',
          'targetMuscle': 'Lats', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Reach one arm overhead and bend to the side.', 'Pull on the wrist gently.', 'Feel the stretch along your side.', 'Switch sides.'],
          'duration': '30s', 'sets': 2, 'reps': 1,
        },
        {
          'id': 'ex_stretching_15', 'name': 'Wrist Stretch', 'categoryId': 'cat_stretching',
          'description': 'Essential for forearm recovery.',
          'targetMuscle': 'Forearms', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Pull your fingers back with your other hand.', 'Keep your arm straight.', 'Rotate for top and bottom stretches.', 'Gentle pressure.'],
          'duration': '30s', 'sets': 2, 'reps': 1,
        },
        {
          'id': 'ex_stretching_16', 'name': 'Sphynx Pose', 'categoryId': 'cat_stretching',
          'description': 'Gentle backbend for spinal health.',
          'targetMuscle': 'Back / Spine', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Lie on your stomach.', 'Prop yourself up on your forearms.', 'Look forward.', 'Keep your hips grounded.'],
          'duration': '45s', 'sets': 2, 'reps': 1,
        },
        {
          'id': 'ex_stretching_17', 'name': 'Downward Dog', 'categoryId': 'cat_stretching',
          'description': 'Full body stretch targeting the posterior chain.',
          'targetMuscle': 'Hamstrings / Back', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Form an inverted V shape.', 'Press your heels toward the floor.', 'Push through your palms.', 'Keep your back straight.'],
          'duration': '45s', 'sets': 2, 'reps': 1,
        },
        {
          'id': 'ex_stretching_18', 'name': 'Seated Glute Stretch', 'categoryId': 'cat_stretching',
          'description': 'Easy way to stretch the outer hip and glute.',
          'targetMuscle': 'Glutes', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Sit with one leg over the other.', 'Pull your knee toward your chest.', 'Rotate your torso.', 'Switch sides.'],
          'duration': '30s', 'sets': 2, 'reps': 1,
        },
        {
          'id': 'ex_stretching_19', 'name': 'Spinal Twist (Lying)', 'categoryId': 'cat_stretching',
          'description': 'Relieves lower back tension.',
          'targetMuscle': 'Lower Back / Spine', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Lie on your back.', 'Drop your knees to one side.', 'Keep your shoulders on the floor.', 'Look in the opposite direction.'],
          'duration': '45s', 'sets': 2, 'reps': 1,
        },
        {
          'id': 'ex_stretching_20', 'name': 'Deep Squat Hold', 'categoryId': 'cat_stretching',
          'description': 'Improves hip mobility and ankle flexibility.',
          'targetMuscle': 'Hips / Ankles', 'difficulty': 'Intermediate', 'gifUrl': gifUrl,
          'steps': ['Sit in the bottom of a squat.', 'Keep your heels on the ground.', 'Use your elbows to push your knees out.', 'Hold with a straight back.'],
          'duration': '60s', 'sets': 1, 'reps': 1,
        },
        {
          'id': 'ex_stretching_21', 'name': 'Wrist Circles', 'categoryId': 'cat_stretching',
          'description': 'Restores mobility to the wrists.',
          'targetMuscle': 'Wrists', 'difficulty': 'Beginner', 'gifUrl': gifUrl,
          'steps': ['Rotate your wrists in both directions.', 'Keep it slow and controlled.', 'Maintain soft movements.', 'Repeat.'],
          'duration': '30s', 'sets': 2, 'reps': 10,
        },
      ],
      'plans': [
        {'day': 'Monday', 'targetMuscle': 'Chest & Cardio', 'exerciseIds': ['ex_chest_1', 'ex_chest_4', 'ex_chest_7', 'ex_chest_15', 'ex_cardio_6']},
        {'day': 'Tuesday', 'targetMuscle': 'Back & Forearms', 'exerciseIds': ['ex_back_2', 'ex_back_4', 'ex_back_7', 'ex_forearms_7', 'ex_forearms_1']},
        {'day': 'Wednesday', 'targetMuscle': 'Legs & Cardio', 'exerciseIds': ['ex_legs_1', 'ex_legs_3', 'ex_legs_7', 'ex_legs_13', 'ex_cardio_5']},
        {'day': 'Thursday', 'targetMuscle': 'Shoulders & Stretching', 'exerciseIds': ['ex_shoulders_1', 'ex_shoulders_3', 'ex_shoulders_7', 'ex_stretching_1', 'ex_stretching_3']},
        {'day': 'Friday', 'targetMuscle': 'Biceps & Triceps', 'exerciseIds': ['ex_bicep_1', 'ex_bicep_3', 'ex_tricep_1', 'ex_tricep_3', 'ex_tricep_5']},
        {'day': 'Saturday', 'targetMuscle': 'Full Body Cardio', 'exerciseIds': ['ex_cardio_1', 'ex_cardio_4', 'ex_cardio_10', 'ex_cardio_13', 'ex_cardio_20']},
        {'day': 'Sunday', 'targetMuscle': 'Rest & Stretching', 'exerciseIds': ['ex_stretching_4', 'ex_stretching_5', 'ex_stretching_7', 'ex_stretching_12', 'ex_stretching_20']},
      ]
    };
  }
}
